DROP TABLE PARKINGLOT_TBL;
CREATE TABLE PARKINGLOT_TBL (
	CAR_NO VARCHAR2(20 BYTE) NOT NULL,
	MODEL  VARCHAR2(20 BYTE) NOT NULL
);

ALTER TABLE PARKINGLOT_TBL
	ADD CONSTRAINT PK_PARKINGLOT PRIMARY KEY(CAR_NO);
	
SELECT CAR_NO, MODEL
  FROM PARKINGLOT_TBL;